### ISSUE TITLE
Multiple watchers

### ISSUE THREAD

**Issue by jtangelder** [shama/gulp-webpack#33]
I want to run multiple watchers, i have 2 separate webpack entries with both other configurations + my regular gulp watch tasks. When i run the webpack tasks with `watch: true`, it hangs on the first task. 

If i disable the `watch` argument, everything runs fine, but then i loose the awesome caching (quick rebuild) feature of webpack.

**Comment by shama** [comment]
It's likely you don't need to run multiple watchers. Otherwise, since watching is a process gobbling event you would probably need to run them in separate processes.

**Comment by steida** [comment]
@jtangelder How did you solved it?

**Comment by steida** [comment]
It seems If gulp.watch task is declared first, then it works.

`gulp.task 'default', ['watch', 'client', 'server']`

**Comment by shama** [comment]
Closing per my comment above.

**Comment by steida** [comment]
Please can you explain "It's likely you don't need to run multiple watchers."? What If I need two separate scripts?

**Comment by shama** [comment]
idk, I've always just used gulp's watch and never needed webpack's watch. I don't understand why anyone would need to run both simultaneously.

**Comment by steida** [comment]
If you program consists of many files, the incremental build is must. Sorry, rebuild everything without incremental build is no-go for regular projects.

**Comment by shama** [comment]
Incremental builds seem to work ok for me with webpack using gulp's watch.

**Comment by naorye** [comment]
@shama Are you sure incremental builds works for you with gulp's watch?
Can you explain how to verify it?

Thanks,
NaorYe

**Comment by shama** [comment]
@naorye I pushed an example: https://github.com/shama/webpack-stream/tree/master/examples/incremental-builds

**Comment by naorye** [comment]
@shama Thanks!
