### ISSUE TITLE
Webpack watch prevents further gulp execution

### ISSUE THREAD

**Issue by jtangelder** [shama/gulp-webpack#37]
When running webpack with the watch option set to true, it prevents any further execution of gulp tasks. 
Any tricks to fix this? I want to use also my other gulp tasks that run with gulp-watch. 

````
[10:17:54] Starting 'webpack'...
[10:18:06] Version: webpack 1.5.3
        Asset     Size  Chunks             Chunk Names
    vendor.js  1776086       0  [emitted]  vendor
       app.js  1720552       1  [emitted]  app
vendor.js.map  2105617       0  [emitted]  vendor
   app.js.map  2131789       1  [emitted]  app
[10:18:06] Webpack is watching for changes
````

**Comment by davepies** [comment]
I have the same problem.

Would be happy if anyone has an idea on how to get around this.

**Comment by binarykitchen** [comment]
Same here ...

**Comment by shama** [comment]
Why not just use gulp's watch? It seems to work better with gulp.

I'm open to a PR if it's a fairly simple fix although I personally don't see the point; just use gulp's watch. 

But for an actual fix it's likely you'll need to bring it up with webpack itself as gobbling the process to sit and watch files forever is a typical behavior of watch. So closing this issue again. Thanks!

**Comment by binarykitchen** [comment]
Yeah, gulp.watch is better from a theoretical perspective. Problem is just speed, performance. It is too slow with gulp.watch. I reverted, removed gulp-webpack and am using the plain webpack, cache the compiler and use gulp.watch at last. Like that, everything works fine and speed is good. But not with this gulp plugin.

**Comment by shama** [comment]
:+1: that works too.

**Comment by vinnymac** [comment]
I just wanted to say that I did what @binarykitchen proposed and now my builds are extremely fast. I ended up using gulp-webpack for production builds. For development I use gulp-watch for additions/deletions and webpack by default in watch mode. This results in great build times.

**Comment by asundlihardig** [comment]
Hi @vinnymac / @binarykitchen 

Do you have an example on how you gained the speed you are talking about? My webpack is superslow when triggering it using gulp-watch. Probably my gulp-webpack causing this?

**Comment by binarykitchen** [comment]
Do not use gulp-webpack. Just require webpack directly. Cannot give an example as my gulp file is huge. I think the maintainers of webpack should be able to help.

**Comment by asundlihardig** [comment]
Thanks @binarykitchen 

Made it much faster by dropping gulp-webpack. Currently I'm using gulp-webpack for production builds. 

If you don't mind, could you please point me in the direction of how to cache the compiler? ( If you guys did more than cache: true in the config file of course )

And thanks again for answering me the first time:-)
