### ISSUE TITLE
--progress support

### ISSUE THREAD

**Issue by jtangelder** [shama/gulp-webpack#41]
Whould be nice to see the progress while running the webpack task. This can be done with the ProgressPlugin provided by Webpack. 

Example; `webpack --progress`

**Comment by liaa** [comment]
@jtangelder How do you deal with this?

**Comment by jtangelder** [comment]
I defined the ProgressPlugin in my plugins object at the webpack.config;

````js
new webpack.ProgressPlugin(function (percentage, message) {
  constpercent = Math.round(percentage * 100);
  process.stderr.clearLine();
  process.stderr.cursorTo(0);
  process.stderr.write(percent + '% ' + message);
})
````

**Comment by liaa** [comment]
Thank you @jtangelder
