### ISSUE TITLE
Question: why use this?

### ISSUE THREAD

**Issue by kentor** [shama/gulp-webpack#46]
Hi, this may sound like a stupid question but I'm just wondering why we would use this instead of the webpack cli or api? It seems like with the webpack config we can already specify the entry points and outputs. With the gulp plugin we'd have to specify it again with `gulp.src` and `gulp.dest`. Is there some benefit for using this plugin?

**Comment by shama** [comment]
If you want to pipe webpack as part of your gulp plugin stream. webpack doesn't stream natively. If you're not piping webpack to anything then this plugin isn't necessary over plain webpack.
