### ISSUE TITLE
Webpack ignore the stream

### ISSUE THREAD

**Issue by monkeymonk** [shama/gulp-webpack#47]
Hi there!

I'm trying to use `gulp-include` then `gulp-webpack` ...but not succeed for now.
It seems to ignore the `include` part... (I see my `//= require ./thing.js` in the bundled file).

Is anyone know how to fix this?

###### JS task:

```javascript
gulp.src(config.src_dir + '/js/main.js')
        .pipe($.include())
        .pipe($.webpack(config.webpack))

        .pipe(gulp.dest(config.public_dir + '/js'));
```

###### `main.js`

```javascript
console.log('-> main');

// gulp-include:
//= require ./yepee.js
```

###### `yepee.js`

```javascript
console.log('ᕕ( ᐛ )ᕗ <( Yepee! )');
```

**Comment by shama** [comment]
I don't use `gulp-include` so I can't help you there. My guess is you don't need `gulp-include` if you're using webpack. Just `require()` your modules and utilize the benefits of webpack. If you need help jump on webpack's gitter channel: https://gitter.im/webpack/webpack

**Comment by monkeymonk** [comment]
I think the problem is much more somewhere in the pipe... it seems that `webpack` is not using it. This is like the pipes before are ignored.

Just for info, I wanted to use `gulp-include` to structure my angular modules into pieces.
Before require them in the main app using `webpack`.

***Example:***

```yaml
js/
    components/
        amodule/
            amodule.js
            amoduleController.js
```

***`amodule.js`***

```javascript
var angular = require('angular');

angular.module('amodule', []);

//= require ./amoduleController.js
```


***`amoduleController.js`***

```javascript
angular.module('amodule')
.controller('AController', 'AController');

function AController($scope) {
    $scope.text = 'ʕ´•㉨•`ʔ <( Wokin? )';
}
```

**Comment by shama** [comment]
One possible problem is `.pipe($.include())` is likely going to output vinyl files which are fed to webpack as entry points. Is that what you're intending?

But the simple solution is don't use `gulp-include`. It's using regex to find pseudo require pragma to naively concat files for you.

I recommend just using webpack which parses the AST and loads your modules via a dependency graph. It does everything that `gulp-include` is doing (plus a ton more) in a way more robust way.

**Comment by monkeymonk** [comment]
I just want to avoid unnecessary `webpack` things... specially where it is totally superfluous.
I guess I will look for another solution that allow me to `concat` some files ***where I want*** ! :-)
In worst case, I also can save the `gulp-include` work before using `webpack`...

Thank you! ;-)
