### ISSUE TITLE
Problems with multiple entry points and 'named' plugin

### ISSUE THREAD

**Issue by thomasklein** [shama/gulp-webpack#49]
Hi! Thanks for the great plugin to begin with!

Defining multiple entry points (https://github.com/shama/gulp-webpack#multiple-entry-points) with named() does not work as I would expect it.

Let's say I have the structure
```
- a
  - main.js 
- b
  - main.js
```
and apply

```
gulp.src('**/main.js')
  .pipe(named())
  .pipe(webpack())
  .pipe(gulp.dest('dist'));
```
I would aspect in dist to have two compiled bundles as I would get using
```
entry: {
    'one': 'path/to/one.js',
    'two': 'path/to/two.js',
  }
```
but I only get one dist/main.js. Am I doing something wrong?

**Comment by shama** [comment]
Both of your entry points are named `main` so they will conflict. You'll need to modify how `named()` determines the entry point name:

```
named(function(file) {
  return 'your-custom-determined-name'
})
```

Or just don't worry about all that and set the entry points normally with webpack:

```
webpack({
  entry: {
    one: 'a/main.js',
    two: 'b/main.js',
  }
})
.pipe(gulp.dest('dist'))
```

**Comment by thomasklein** [comment]
My bad, worked! Thanks Kyle!
