### ISSUE TITLE
Pipe output from `gulp-mustache` in as webpack entry point

### ISSUE THREAD

**Issue by matthewgertner** [shama/gulp-webpack#52]
The code of the Webpack entry point of my JavaScript app varies for different Gulp tasks, so I am putting it through a Mustache template before piping it to Webpack (using `gulp-mustache` and `gulp-webpack`):

    gulp.task('webpack', function() {
      return gulp.src('./index.js.mustache')
        .pipe(mustache({
          suffix: '.min.js'
        }))
       .pipe(webpack(config))
       .pipe(gulp.dest('dist/js'));
    });

Unfortunately this doesn't work as expected. `gulp-webpack` seems to use the original filename (`index.js.mustache`) rather than the new contents of the file, so the changes made by the Mustache template are ignored.

In order to get it to work I have to say:

    gulp.task('webpack', function() {
      return gulp.src('./index.js.mustache')
        .pipe(mustache({
          suffix: '.min.js'
        }))
       .pipe(rename('index.js'))
       .pipe(gulp.dest('.'))
       .pipe(webpack(config))
       .pipe(gulp.dest('dist/js'));
    });

It seems wrong to me that I have to use an intermediate file though. Is there some way to get `gulp-webpack` to use the stream properly?

**Comment by shama** [comment]
You can modify the name of the entry point using https://github.com/shama/vinyl-named

Or use a mustache webpack loader and handle the compilation there.
